services:
  api-gateway-2:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    # ports:
    #   - 8000:8000
    #   - 50051:50051
    volumes:
      - ./services/api-gateway:/app
    depends_on:
      - feed-service
      - user-service
      - post-service
      - subreddit-service
      - vote-service
      - gateway-cache
    environment:
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=50051
      - POST_SERVICE_HOST=post-service
      - POST_SERVICE_PORT=50051
      - SUBREDDIT_SERVICE_HOST=subreddit-service
      - SUBREDDIT_SERVICE_PORT=50051
      - VOTE_SERVICE_HOST=vote-service
      - VOTE_SERVICE_PORT=50051
      - FEED_SERVICE_HOST=feed-service
      - FEED_SERVICE_PORT=50051
      - REDIS_HOST=gateway-cache
      - REDIS_PORT=6379
      - SECRET_KEY=dev-secret-key
  api-gateway-1:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    # ports:
    #   - 8000:8000
    #   - 50051:50051
    volumes:
      - ./services/api-gateway:/app
    depends_on:
      - feed-service
      - user-service
      - post-service
      - subreddit-service
      - vote-service
      - gateway-cache
    environment:
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=50051
      - POST_SERVICE_HOST=post-service
      - POST_SERVICE_PORT=50051
      - SUBREDDIT_SERVICE_HOST=subreddit-service
      - SUBREDDIT_SERVICE_PORT=50051
      - VOTE_SERVICE_HOST=vote-service
      - VOTE_SERVICE_PORT=50051
      - FEED_SERVICE_HOST=feed-service
      - FEED_SERVICE_PORT=50051
      - REDIS_HOST=gateway-cache
      - REDIS_PORT=6379
      - SECRET_KEY=dev-secret-key

  load-balancer:
    build:
      context: ./services/load-balancer
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - api-gateway-1
      - api-gateway-2

  load-balancer-2:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./services/load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway-1
      - api-gateway-2
  feed-service:
    build:
      context: ./services/feed-service
      dockerfile: Dockerfile
    volumes:
      - ./services/feed-service:/app
    depends_on:
      - post-service
    environment:
      - POST_SERVICE_HOST=post-service
      - POST_SERVICE_PORT=50051
      - PORT=50051

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    volumes:
      - ./services/user-service:/app
      - ./user_db_data:/data
    environment:
      - DB_NAME=user_service.sqlite
      - PORT=50051

  post-service:
    build:
      context: ./services/post-service
      dockerfile: Dockerfile
    volumes:
      - ./services/post-service:/app
      - ./post_db_data:/data
    depends_on:
      - user-service
      - vote-service
    environment:
      - DB_NAME=post_service.sqlite
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=50051
      - VOTE_SERVICE_HOST=vote-service
      - VOTE_SERVICE_PORT=50051
      - PORT=50051

  subreddit-service:
    build:
      context: ./services/subreddit-service
      dockerfile: Dockerfile
    volumes:
      - ./services/subreddit-service:/app
      - ./subreddit_db_data:/data
    environment:
      - DB_NAME=subreddit_service.sqlite
      - PORT=50051

  vote-service:
    build:
      context: ./services/vote-service
      dockerfile: Dockerfile
    volumes:
      - ./services/vote-service:/app
      - ./vote_db_data:/data
    environment:
      - DB_NAME=vote_service.sqlite
      - POST_SERVICE_HOST=post-service
      - POST_SERVICE_PORT=50051
      - PORT=50051


  gateway-cache:
    image: redis:latest
    ports:
      - 6379:6379
