services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 5555:5000
    depends_on:
      - feed-service
      - gateway-cache
  feed-service:
    build:
      context: ./services/feed-service
      dockerfile: Dockerfile
    depends_on:
      - user-service
      - post-service
      - subreddit-service
      - vote-service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    depends_on:
      - user-service-db
    environment:
      - DB_HOST=user-service-db
      - DB_NAME=user_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  post-service:
    build:
      context: ./services/post-service
      dockerfile: Dockerfile
    depends_on:
      - post-service-db
    environment:
      - DB_HOST=post-service-db
      - DB_NAME=post_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  subreddit-service:
    build:
      context: ./services/subreddit-service
      dockerfile: Dockerfile
    depends_on:
      - subreddit-service-db
    environment:
      - DB_HOST=subreddit-service-db
      - DB_NAME=subreddit_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  vote-service:
    build:
      context: ./services/vote-service
      dockerfile: Dockerfile
    depends_on:
      - vote-service-db
    environment:
      - DB_HOST=vote-service-db
      - DB_NAME=vote_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  gateway-cache:
    image: redis:latest
    ports:
      - 6379:6379
  user-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_service
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - user_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  post-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: post_service
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - post_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  subreddit-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: subreddit_service
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - subreddit_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  vote-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: vote_service
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - vote_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user_db_data:
  post_db_data:
  subreddit_db_data:
  vote_db_data:
