all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/gcp-ansible-key
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ProxyCommand='gcloud compute start-iap-tunnel %h 22 --listen-on-stdin --zone=us-west3-a --project=distributed-systems-487323'"
    ansible_user: hamad
  children:
    load_balancers:
      hosts:
        load-balancer-go:
          ansible_host: load-balancer-go
          service: load-balancer
          service_ports:
            - "80:8000"
          container_env:
            SERVER_IPS: "10.180.0.25,10.180.0.26,10.180.0.27"
        load-balancer-nginx:
          ansible_host: load-balancer-nginx
          service: nginx-lb
          service_ports:
            - "80:80"
          container_env:
            BACKENDS: "server 10.180.0.25:8000; server 10.180.0.26:8000; server 10.180.0.27:8000;"

    gateways:
      vars:
        container_env:
          USER_SERVICE_HOST: "10.180.0.28"
          USER_SERVICE_PORT: "50051"
          POST_SERVICE_HOST: "10.180.0.29"
          POST_SERVICE_PORT: "50051"
          SUBREDDIT_SERVICE_HOST: "10.180.0.30"
          SUBREDDIT_SERVICE_PORT: "50051"
          VOTE_SERVICE_HOST: "10.180.0.31"
          VOTE_SERVICE_PORT: "50051"
          FEED_SERVICE_HOST: "10.180.0.32"
          FEED_SERVICE_PORT: "50051"
          REDIS_HOST: "10.180.0.33"
          REDIS_PORT: "6379"
          SECRET_KEY: "prod-secret-key"
      hosts:
        api-gateway-0:
          ansible_host: api-gateway-0
          service: api-gateway
          service_ports: ["8000:8000", "50051:50051"]
        api-gateway-1:
          ansible_host: api-gateway-1
          service: api-gateway
          service_ports: ["8000:8000", "50051:50051"]
        api-gateway-2:
          ansible_host: api-gateway-2
          service: api-gateway
          service_ports: ["8000:8000", "50051:50051"]

    backend_services:
      hosts:
        user-service:
          ansible_host: user-service
          service: user-service
          service_ports: ["50051:50051"]
          service_volumes: ["user_db_data:/data"]
        post-service:
          ansible_host: post-service
          service: post-service
          service_ports: ["50051:50051"]
          service_volumes: ["post_db_data:/data"]
          container_env:
            USER_SERVICE_HOST: "10.180.0.28"
            USER_SERVICE_PORT: "50051"
            VOTE_SERVICE_HOST: "10.180.0.31"
            VOTE_SERVICE_PORT: "50051"
        subreddit-service:
          ansible_host: subreddit-service
          service: subreddit-service
          service_ports: ["50051:50051"]
          service_volumes: ["subreddit_db_data:/data"]
        vote-service:
          ansible_host: vote-service
          service: vote-service
          service_ports: ["50051:50051"]
          service_volumes: ["vote_db_data:/data"]
          container_env:
            POST_SERVICE_HOST: "10.180.0.29"
            POST_SERVICE_PORT: "50051"
        feed-service:
          ansible_host: feed-service
          service: feed-service
          service_ports: ["50051:50051"]
          container_env:
            POST_SERVICE_HOST: "10.180.0.29"
            POST_SERVICE_PORT: "50051"

    infrastructure:
      hosts:
        gateway-cache:
          ansible_host: gateway-cache
          service: gateway-cache
          service_ports: ["6379:6379"]
